### ISSUE TITLE
Error when playing mp3

### ISSUE THREAD

**Issue by ManuCart** [Pat-Carter/stream2chromecast#14] opened 2016-08-04 14:09 UTC
````
python stream2chromecast.py ok.mp3
searching the network for a Chromecast device
device name: Freebox Player Mini
Playing: /home/pi/.bin/stream2chromecast/ok.mp3
avconv version 11.7-6:11.7-1~deb8u1+rpi1, Copyright (c) 2000-2016 the Libav developers
  built on Jun 17 2016 02:13:49 with gcc 4.9.2 (Raspbian 4.9.2-10)
unable to find ffmpeg - using avconv
OS identifies the mimetype as : audio/mpeg
my ip address: 192.168.0.1
URL & content-type:  http://192.168.0.1:38975/home/pi/.bin/stream2chromecast/ok.mp3 audio/mpeg
loading media...
192.168.0.11 - - [04/Aug/2016 16:01:41] "GET /home/pi/.bin/stream2chromecast/ok.mp3 HTTP/1.1" 200 -
sending file
----------------------------------------
Exception happened during processing of request from ('192.168.0.11', 54466)
Traceback (most recent call last):
  File "/usr/lib/python2.7/SocketServer.py", line 295, in _handle_request_noblock
    self.process_request(request, client_address)
  File "/usr/lib/python2.7/SocketServer.py", line 321, in process_request
    self.finish_request(request, client_address)
  File "/usr/lib/python2.7/SocketServer.py", line 334, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib/python2.7/SocketServer.py", line 657, in __init__
    self.finish()
  File "/usr/lib/python2.7/SocketServer.py", line 716, in finish
    self.wfile.close()
  File "/usr/lib/python2.7/socket.py", line 279, in close
    self.flush()
  File "/usr/lib/python2.7/socket.py", line 303, in flush
    self._sock.sendall(view[write_offset:write_offset+buffer_size])
error: [Errno 32] Broken pipe
----------------------------------------
^C
stopping...
````

**Comment by Pat-Carter** [comment] 2016-08-04 14:18
Is this actually a Chromecast?

This sounds like another issue experienced by someone else who was using an Amazon Firestick or something similar.

The error is caused by the device closing the connection whilst we're trying to send the file.

**Comment by ManuCart** [comment] 2016-08-04 14:24
Following issue #4 your link work for me very well
````python stream2chromecast.py -playurl http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4````
but for this link
````
python stream2chromecast.py -playurl http://hi5.streamingsoundtracks.com ````
I have this error (It's only music)
````
Traceback (most recent call last):
  File "stream2chromecast.py", line 572, in <module>
    run()
  File "stream2chromecast.py", line 562, in run
    playurl(arg2, device_name=device_name)
  File "stream2chromecast.py", line 415, in playurl
    resp = conn.getresponse()
  File "/usr/lib/python2.7/httplib.py", line 1073, in getresponse
    response.begin()
  File "/usr/lib/python2.7/httplib.py", line 415, in begin
    version, status, reason = self._read_status()
  File "/usr/lib/python2.7/httplib.py", line 379, in _read_status
    raise BadStatusLine(line)
httplib.BadStatusLine: ''
````
may be I need to transcode but I don't know how

**Comment by ManuCart** [comment] 2016-08-04 14:30
I allredy use castnow
https://github.com/xat/castnow

And with this command it' working
````
castnow "http://hi5.streamingsoundtracks.com" --type "audio/wav"
````

but I want to use your python script because for my raspberry pi it's faster

**Comment by Pat-Carter** [comment] 2016-08-04 14:30
I'm afraid I only have a Chromecast.

...so I can only guess, but I think that some other devices don't like the format of the HTTP response we send them to serve the file.

Perhaps you could try the transcode option as it sends the response back in a slightly different format.

e.g. 
python stream2chromecast.py -transcode ok.mp3

cheers,

Pat

**Comment by ManuCart** [comment] 2016-08-04 14:39
Now my file ok.mp3 work fine but not my stream link
````
python stream2chromecast.py -playurl http://hi5.streamingsoundtracks.com
````

**Comment by Pat-Carter** [comment] 2016-08-04 14:45
is that actually a media URL?

It looks like a straight web page to me.

**Comment by ManuCart** [comment] 2016-08-04 14:51
Yes it's a media url
just put the link in vlc and it's playing

http://www.streamingsoundtracks.com/modules.php?name=Listen

**Comment by Pat-Carter** [comment] 2016-08-04 15:01
I think I understand.

-playurl doesn't play a shoutcast stream. It plays a file that is available on a URL.

I think that URL is a streaming server (rather than a file server).

Could you try this one, please?

python stream2chromecast.py -playurl 'http://www.stephaniequinn.com/Music/Handel%20-%20Entrance%20of%20the%20Queen%20of%20Sheba.mp3'

**Comment by ManuCart** [comment] 2016-08-04 15:19
Your link work and I understand what you say but I explain bellow with castnow it's working

````
castnow "http://hi5.streamingsoundtracks.com" --type "audio/wav"
````

Is there an option with stream2chromecast.py to tell it's wav format

**Comment by ManuCart** [comment] 2016-08-04 15:36
Yes that stream doesn't have a file size, ok too bad
So nice python script and fast

**Comment by Pat-Carter** [comment] 2016-08-04 15:43
Sorry about that.

I'll see if I can work out why your ok.mp3 needed to be transcoded.

**Comment by Pat-Carter** [comment] 2016-08-04 16:25
Hi,

Could you grab the latest version of stream2chromecast.py and try your ok.mp3 again, please - but this time without the transcode option.

**Closed** 2016-08-21 16:34 UTC
